### ISSUE TITLE
Can't seem to get it to run correctly

### ISSUE THREAD

**Issue by wavesailor** [archy-bold/prem-stats#1]
Hi Simon,

Found your link on the toptal site. I'm new to Node, Angular etc.
Been trying to get this to work. I registered for access to the API @ http://football-api.com
I cloned your git repository, then ran npm install, bower install and then npm start but I'm not getting any information returned - just a blank **Premier League Table**
I found some API errors in the file `app.js` which I fixed
`url: 'http://football-api.com/api/?APIKey=xxxxx'`
`url: footballAPI.url + '&Action=standings&comp_id=1204'`
`url: footballAPI.url + '&Action=fixtures'`

Any ideas where to check to resolve this?
Thx

**Comment by archy-bold** [comment]
Hi wavesailor. Cheers for checking out my repo, it's really appreciated :)

Yeah, I should have updated the Readme with some info on this. There are a couple of issues going on here. The first is that I didn't want to publish my API key and the second is that football-api.com doesn't allow Cross-domain ajax.

To resolve both these issues, I set up a simple PHP script `api.php` to basically act as a proxy for all requests to the API. Do you have PHP on your server/machine?

If so, you can do the following.
1. Undo the changes you've made.
2. Change the URL on line 21 to be that of your application, it could be that you're running on localhost, so whatever is in the address bar. api.php is referring to the script I prepared for the request routing.
   `
   var footballAPI = {
       url: 'http://url-to/your-application/api.php'
   };
   `
3. Add a new file `api-key.php` in the `public/` directory with the following code, swapping for your API key.
   `
   <?php
   $key = 'YOUR-API-KEY';
   `

Let me know if you have any more issues, but that _should_ fix it.

Cheers,
Simon

**Comment by wavesailor** [comment]
Hi Simon,
Ah okay - Thanks - That makes a bit more sense but I'm still stuck.
I modified the line the URL on line 21. I tired both the following but neither worked:

`http://localhost:8000/api.php`  (That's the Node app) - If I enter this directly in browser then it wants to serve up the actual file i.e. download api.php

`http://localhost/api.php`  (That's via Apache)  - If I enter this directly in browser with `?action=standings&comp_id=1204'` appended then I get the correct JSON data

But the NodeJs App still displays an empty  _Premier League Table_
Think I'm missing something small here
Cheers,
Grant

**Comment by archy-bold** [comment]
Yeah, you don't want to go via node because node isn't capable of processing PHP code, so the second is definitely the correct one.

Can you open up the console in your browser (Inspect Element in Chrome) and let me know what errors you're getting in the console? `http://localhost/api.php` is definitely going to be the correct URL.

**Comment by wavesailor** [comment]
Thanks for help
Running under apache: `http://localhost/api.php` with this added `?action=standings&comp_id=1204'` returns the correct information i.e. I get the "standings" JSON information.
My problem is that the NodeJS app does not work ... But now under chrome I see some errors:
`GET http://localhost:8000/%7B%7Bteam.Team.badge%7D%7D 404 (Not Found) angular.js:3200`
`XMLHttpRequest cannot load http://localhost/api.php?action=standings&comp_id=1204. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

I googled and tried different options but they didn't work.

**Comment by archy-bold** [comment]
You don't actually need to run a node server. Try going to http://localhost/
<http://localhost/api.php> in your browser

On Friday, 21 August 2015, wavesailor <notifications@github.com> wrote:

> Thanks for help
> Running under apache: http://localhost/api.php with this added
> ?action=standings&comp_id=1204' returns the correct information i.e. I
> get the "standings" JSON information.
> My problem is that the NodeJS app does not work ... But now under chrome I
> see some errors:
> GET http://localhost:8000/%7B%7Bteam.Team.badge%7D%7D 404 (Not Found)
> angular.js:3200
> XMLHttpRequest cannot load
> http://localhost/api.php?action=standings&comp_id=1204. No
> 'Access-Control-Allow-Origin' header is present on the requested resource.
> Origin 'http://localhost:8000' is therefore not allowed access.
>
> I googled and tried different options but they didn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archy-bold/prem-stats/issues/1#issuecomment-133406022>
> .
>


-- 

*Simon "archybold" Archer* | Freelance and Contract Web Developer

@archy_bold <https://twitter.com/archy_bold> | LinkedIn
<http://uk.linkedin.com/in/archybold> | archybold.com
<http://www.archybold.com> | realmanctech.com <http://www.realmanctech.com/>

**Comment by archy-bold** [comment]
You don't actually need to run a node server. Try going to `http://localhost/` in your browser, not to port 8000, it should just work.

On Friday, 21 August 2015, Simon Archer simon@archybold.com wrote:

> You don't actually need to run a node server. Try going to
> http://localhost/ http://localhost/api.php in your browser
> 
> On Friday, 21 August 2015, wavesailor <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Thanks for help
> > Running under apache: http://localhost/api.php with this added
> > ?action=standings&comp_id=1204' returns the correct information i.e. I
> > get the "standings" JSON information.
> > My problem is that the NodeJS app does not work ... But now under chrome
> > I see some errors:
> > GET http://localhost:8000/%7B%7Bteam.Team.badge%7D%7D 404 (Not Found)
> > angular.js:3200
> > XMLHttpRequest cannot load
> > http://localhost/api.php?action=standings&comp_id=1204. No
> > 'Access-Control-Allow-Origin' header is present on the requested resource.
> > Origin 'http://localhost:8000' is therefore not allowed access.
> > 
> > I googled and tried different options but they didn't work.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/archy-bold/prem-stats/issues/1#issuecomment-133406022
> > .
> 
> ## 
> 
> _Simon "archybold" Archer_ | Freelance and Contract Web Developer
> 
> @archy_bold https://twitter.com/archy_bold | LinkedIn
> http://uk.linkedin.com/in/archybold | archybold.com
> http://www.archybold.com | realmanctech.com
> http://www.realmanctech.com/

## 

_Simon "archybold" Archer_ | Freelance and Contract Web Developer

@archy_bold https://twitter.com/archy_bold | LinkedIn
http://uk.linkedin.com/in/archybold | archybold.com
http://www.archybold.com | realmanctech.com http://www.realmanctech.com/

**Comment by wavesailor** [comment]
Hey Simon,
That part works -  `http://localhost/api.php`
It returns:

```
{"APIVersion":1,"APIRequestsRemaining":994,"DeveloperAuthentication":"TRUE","teams":[{"stand_id":"12049259","stand_competition_id":"1204","stand_season":"2015\/2016","stand_round":"2","stand_stage_id":"12041081","stand_group":"","stand_country":"England","stand_team_id":"9259","stand_team_name":"Manchester City","stand_status":"same","stand_recent_form":"WW","stand_position":"1","stand_overall_gp":"2","stand_overall_w":"2","stand_overall_d":"0","stand_overall_l":"0","stand_overall_gs":"6","stand_overall_ga":"0","stand_home_gp":"1","stand_home_w":"1","stand_home_d":"0","stand_home_l":"0","stand_home_gs":"3","stand_home_ga":"0","stand_away_gp":"1","stand_away_w":"1","stand_away_d":"0","stand_away_l":"0","stand_away_gs":"3","stand_away_ga":"0","stand_gd":"6","stand_points":"6","stand_desc":"Promotion - Champions League (Group Stage)"},{"stand_id":"12049240","stand_competition_id":"1204","stand_season":"2015\/2016","stand_round":"2","stand_stage_id":"12041081","stand_group":"","stand_country":"England","stand_team_id":"9240","stand_team_name":"Leicester","stand_status":"same","stand_recent_form":"WW","stand_position":"2","stand_overall_gp":"2","stand_overall_w":"2","stand_overall_d":"0","stand_overall_l":"0","stand_overall_gs":"6","stand_overall_ga":"3","stand_home_gp":"1","stand_home_w":"1","stand_home_d":"0","stand_home_l":"0","stand_home_gs":"4","stand_home_ga":"2","stand_away_gp":"1","stand_away_w":"1","stand_away_d":"0","stand_away_l":"0","stand_away_gs":"2","stand_away_ga":"1","stand_gd":"3","stand_points":"6","stand_desc":"Promotion - Champions League (Group Stage)"},
```

I now want to run your Angular Node app - That what is not working for me

**Comment by archy-bold** [comment]
In the browser, just go to `http://localhost/` or `
http://localhost/index.html`. It should work.

It's not actually a node app.

On Fri, Aug 21, 2015 at 4:26 PM, wavesailor notifications@github.com
wrote:

> Hey Simon,
> That part works - http://localhost/api.php
> It returns:
> 
> {"APIVersion":1,"APIRequestsRemaining":994,"DeveloperAuthentication":"TRUE","teams":[{"stand_id":"12049259","stand_competition_id":"1204","stand_season":"2015\/2016","stand_round":"2","stand_stage_id":"12041081","stand_group":"","stand_country":"England","stand_team_id":"9259","stand_team_name":"Manchester City","stand_status":"same","stand_recent_form":"WW","stand_position":"1","stand_overall_gp":"2","stand_overall_w":"2","stand_overall_d":"0","stand_overall_l":"0","stand_overall_gs":"6","stand_overall_ga":"0","stand_home_gp":"1","stand_home_w":"1","stand_home_d":"0","stand_home_l":"0","stand_home_gs":"3","stand_home_ga":"0","stand_away_gp":"1","stand_away_w":"1","stand_away_d":"0","stand_away_l":"0","stand_away_gs":"3","stand_away_ga":"0","stand_gd":"6","stand_points":"6","stand_desc":"Promotion - Champions League (Group Stage)"},{"stand_id":"12049240","stand_competition_id":"1204","stand_season":"2015\/2016","stand_round":"2","stand_stage_id":"12041081","stand_group":""
>  ,"stand_country":"England","stand_team_id":"9240","stand_team_name":"Leicester","stand_status":"same","stand_recent_form":"WW","stand_position":"2","stand_overall_gp":"2","stand_overall_w":"2","stand_overall_d":"0","stand_overall_l":"0","stand_overall_gs":"6","stand_overall_ga":"3","stand_home_gp":"1","stand_home_w":"1","stand_home_d":"0","stand_home_l":"0","stand_home_gs":"4","stand_home_ga":"2","stand_away_gp":"1","stand_away_w":"1","stand_away_d":"0","stand_away_l":"0","stand_away_gs":"2","stand_away_ga":"1","stand_gd":"3","stand_points":"6","stand_desc":"Promotion - Champions League (Group Stage)"},
> 
> I now want to run your Angular Node app - That what is not working for me
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/archy-bold/prem-stats/issues/1#issuecomment-133462485
> .

## 

_Simon "archybold" Archer_ | Freelance and Contract Web Developer

@archy_bold https://twitter.com/archy_bold | LinkedIn
http://uk.linkedin.com/in/archybold | archybold.com
http://www.archybold.com | realmanctech.com http://www.realmanctech.com/

**Comment by wavesailor** [comment]
Ha ha ha ... Okay ... got you :-)

## Now It Works !!!

Thanks Simon

**Comment by archy-bold** [comment]
BOOM! No problem Grant. Hope you get some use from it.
